# Generated by Django 2.2.3 on 2019-09-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('userate', models.FloatField()),
                ('phone_rate', models.FloatField(blank=True, null=True)),
                ('pc_rate', models.FloatField(blank=True, null=True)),
                ('notebook_rate', models.FloatField(blank=True, null=True)),
                ('etc_rate', models.FloatField(blank=True, null=True)),
                ('pad_rate', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
